---
title: "Cleaning the data"
output: html_document
date: "2023-10-04"
---

```{r}
#Group the dataset by genres for easy overview
Grouped_by_genres <- merged_ratings_genres %>% 
  group_by(genres) %>%  
  summarize (N_genres=n())

#Find the average ratings for each movie
average_ratings <- merged_ratings_genres %>%
  group_by(genres) %>%
  summarise(Average_Rating = mean(average_ratings, na.rm = TRUE))

#Merge the ratings with the genres to have them in one dataset
merged_average_ratings <- left_join(average_ratings, Grouped_by_genres, by = 'genres')

#Calculate the total ratings for further research
merged_average_ratings <- merged_average_ratings %>% 
  mutate(total_rating = Average_Rating * N_genres)
                              
```

```{r}

#Loop through all the genres to find out how many movies per genre there are. Since many movies have multiple genres, these had to be calculated multiple times. 
all_genres <- c()

for (genres in merged_average_ratings) {
  genres_in_row <- unlist(strsplit(merged_average_ratings$genres[genres], ","))
  genres_in_row <- genres_in_row [genres_in_row != '\\N']
  all_genres <- c(all_genres, unlist(genres_in_row))
}

unique_genres <- unique(all_genres)
unique_genres <- unique_genres [!is.na (unique_genres)]
print (unique_genres)

number_per_genre <- c()

for (genre in unique_genres) { 
  total_of_genres <- Grouped_by_genres %>%  
    filter(grepl(genre, genres)) %>% 
    summarize (sum_of_N_genres = sum(N_genres))
  number_per_genre <- c(number_per_genre, total_of_genres$sum_of_N_genres)
}

print(number_per_genre)

```

```{r}
#Create a dataset for that includes the genres and the number of movies that have that genre
N_genres_dataset <- data.frame(
  genre = unique_genres,
  number = number_per_genre
)

```

```{r}
#Loop through the genres to obtain the total ratings per genre
genre_ratings <- c()

for (genre in unique_genres) {
  total_rating <- sum(merged_average_ratings$total_rating[grepl(genre, merged_average_ratings$genres)], na.rm=TRUE)
  genre_ratings <- rbind(genre_ratings, data.frame(genre = genre, total_rating = total_rating))
}
```

```{r}
#Merge the datasets to obtain a dataset that has the average ratings per genre
merged_genres_total_ratings <- left_join(genre_ratings, N_genres_dataset, by = 'genre')

merged_genres_total_ratings <- merged_genres_total_ratings %>% 
  mutate(average_rating_per_genre = total_rating / number)
```

```{r}
#Calculate the overall average rating that might be usefull for further research
sum_ratings = sum(merged_average_ratings$total_rating, na.rm = TRUE)
sum_genres = sum(merged_average_ratings$N_genres)

average_rating_total <- sum_ratings / sum_genres
```